name: Docker Image CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build the Docker image
        run: |
          docker version
          # 登录阿里云镜像仓库
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
          # 使用Dockerfile构建镜像
          docker build . --file src/main/docker/Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/sunrise2021/hello:0.0.1
          # 推送镜像到镜像仓库
          docker push registry.cn-hangzhou.aliyuncs.com/sunrise2021/hello:0.0.1
